export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_QUANRIRY = "INCREASE_QUANRIRY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
